# Site settings
name: 汪新宇
location: 武汉
company: 武汉婚芭莎
position:web开发工程师
github: https://github.com/
blog: https://www.cnblogs.com/wxyblog/
phone: 1772782xxxx
email: wxy1376258881@163.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

